FROM oven/bun:1

WORKDIR /usr/src/app
ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}
COPY ./packages ./packages
COPY ./bun.lockb ./bun.lockb
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

RUN bun install
COPY ./apps/web ./apps/web



RUN bun run db:generate
RUN bun run build

EXPOSE 3000

CMD [ "bun","run","start:web" ]