FROM oven/bun:1

WORKDIR /usr/src/app
ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}
COPY ./packages ./packages
COPY ./bun.lockb ./bun.lockb

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json


RUN bun install
COPY ./apps/backend ./apps/backend



EXPOSE 8080

CMD bun run db:push && bun run db:generate && bun run start:backend
